#page title
page_title                                :                                          # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 1534997088                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
presskit_download_link                    :                                           # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  :                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : The app to use WhatsApp with phone numbers.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : Juan Cazalla Estrella                                
your_link                                 : https://twitter.com/juan_cazalla
your_city                                 : Spain 🇪🇸                                
email_address                             : cazallasquared@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : juan_cazalla
github_username                           : juancazalla
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Direct Chat To WhatsApp
    description                           : Bye bye ghost contacts. You can write the number and send messages without saving it in your contacts. Voilá!
    fontawesome_icon_name                 : star
    
  - title                                 : Predefined Messages
    description                           : Do you usually write the same messages? Save them and stop losing your time. 
    fontawesome_icon_name                 : list

  - title                                 : Chat To Yourself
    description                           : Save documents and private messages by texting yourself. That's magic!
    fontawesome_icon_name                 : magic

  - title                                 : iCloud Syncing
    description                           : Use different devices with the same iCloud account and share your messages will be available in all of them.
    fontawesome_icon_name                 : sync

  - title                                 : Dark Mode
    description                           : Perfect for night usage, so the timer doesn't light up your room.
    fontawesome_icon_name                 : moon
  
  - title                                 : Check Unknown Phone Numbers
    description                           : Who called? Just copy the number, open Dialer for WhatsApp and navigate to the WhatsApp profile of unknown numbers.
    fontawesome_icon_name                 : user-secret

  - title                                 : # New Feature Title
    description                           : # New Feature Description
    fontawesome_icon_name                 : # Enter Font Awesome icon name (e.g. star). Find icons on fontawesome.com/icons.



# Theme Settings
topbar_color                              : "#ffffff"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                   # Replace with alternative image path or image URL.
cover_overlay_color                       : "#191E33"
cover_overlay_transparency                : 1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#1d63ea"

app_title_color                           : "#ffffff"
app_price_color                           : "#f3f3f3"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown